repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    - id: black
      language_version: python3.10
  - repo: local
    hooks:
    - id: mypy_package
      name: mypy_package
      entry: poetry run mypy ./weather_api/
      pass_filenames: false
      language: python
      types:
      - python
    - id: mypy_tests
      name: mypy_tests
      entry: poetry run mypy ./tests/
      pass_filenames: false
      language: python
      types:
      - python
    - id: mypy_airflow
      name: mypy_airflow
      entry: bash run_mypy_airflow.sh
      language: system
    - id: pylint
      name: pylint
      entry: poetry run pylint ./weather_api/ ./tests
      language: python
      pass_filenames: false
      types:
      - python
    - id: pylint_airflow
      name: pylint_airflow
      entry: bash run_pylint_airflow.sh
      language: system