repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    - id: mypy
      args: [--config-file=.github/linters/.mypy.ini]
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    - id: black
      language_version: python3.8
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint ./weather_api/
      language: python
      types:
      - python