repos:
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint .
      language: python
      types:
      - python
    - id: black
      name: black
      entry: poetry run black .
      language: python
      types:
      - python
    - id: mypy
      name: mypy
      entry: poetry run mypy .
      language: python
      types:
      - python